# Generated by Django 4.2.6 on 2023-11-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_inital',
        ),
        migrations.AddField(
            model_name='post',
            name='last_initial',
            field=models.CharField(default='j', max_length=5),
            preserve_default=False,
        ),
    ]
