# Generated by Django 4.2.6 on 2023-11-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipper', '0002_remove_post_last_inital_post_last_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bill',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='tip',
            field=models.CharField(max_length=15),
        ),
    ]
