# Generated by Django 4.2.6 on 2023-11-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipper', '0003_alter_post_bill_alter_post_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bill',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='tip',
            field=models.FloatField(),
        ),
    ]
